<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

# Hands-on Lab: API Examples
## Random User and Fruityvice API Examples


Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Load and use RandomUser API, using `RandomUser()` Python library
*   Load and use Fruityvice API, using `requests` Python library
*   Load and use Open-Joke-API, using `requests` Python library

The purpose of this notebook is to provide more examples on how to use simple APIs. As you have already learned from previous videos and notebooks, API stands for Application Programming Interface and is a software intermediary that allows two applications to talk to each other. 

The advantages of using APIs:
 *   **Automation**. Less human effort is required and workflows can be easily updated to become faster and more      
     productive.
 *   **Efficiency**. It allows to use the capabilities of one of the already developed APIs than to try to 
     independently implement some functionality from scratch.
 
The disadvantage of using APIs:
 *   **Security**. If the API is poorly integrated, it means it will be vulnerable to attacks, resulting in data breeches or losses having financial or reputation implications.

One of the applications we will use in this notebook is Random User Generator. RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more. More information on [RandomUser](https://randomuser.me/documentation#intro) can be found here.

Another example of simple API we will use in this notebook is Fruityvice application. The Fruityvice API web service which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The web service is completely free to use and contribute to.

## Example 1: RandomUser API
Bellow are Get Methods parameters that we can generate. For more information on the parameters, please visit this [documentation](https://randomuser.me/documentation) page.

## **Get Methods**

- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

To start using the API you can install the `randomuser` library running the `pip install` command.

In [1]:
!pip install randomuser
!pip install pandas

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py) ... one
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5104 sha256=7513e2c69dcdfdc27c2dab2eb8be9d10c7c80dbc4f5406ed580c51e790bae516
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/be/62/c8/71e1b48f4758ea5b78af7595d87178f628cde315a3326610ee
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6
Collecting pandas
  Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 178.0 MB/s eta 0:00:00
Downloading numpy-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 198.4 MB/s eta 0:00:00
Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.2.2 pandas-2.2.3 tzdata-2025.1

Then, we will load the necessary libraries.

In [2]:
from randomuser import RandomUser
import pandas as pd

First, we will create a random user object, r.

In [3]:
r = RandomUser()

Then, using `generate_users()` function, we get a list of random 10 users.

In [4]:
some_list = r.generate_users(10)

In [5]:
some_list

[<randomuser.RandomUser at 0x7fb0c0277890>,
 <randomuser.RandomUser at 0x7fb0c02778c0>,
 <randomuser.RandomUser at 0x7fb0c02778f0>,
 <randomuser.RandomUser at 0x7fb0c0277920>,
 <randomuser.RandomUser at 0x7fb0c0277950>,
 <randomuser.RandomUser at 0x7fb0c0277980>,
 <randomuser.RandomUser at 0x7fb0c02779b0>,
 <randomuser.RandomUser at 0x7fb0c02779e0>,
 <randomuser.RandomUser at 0x7fb0c0277a10>,
 <randomuser.RandomUser at 0x7fb0c0277a40>]

The **"Get Methods"** functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call `get_full_name()` function.

In [7]:
name = r.get_full_name()

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

In [8]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Savannah Thomas   savannah.thomas@example.com
Valtteri Wainio   valtteri.wainio@example.com
Dylan Davies   dylan.davies@example.com
Fride Bhatti   fride.bhatti@example.com
Wesley Rogers   wesley.rogers@example.com
Anna Suarez   anna.suarez@example.com
Livia Joly   livia.joly@example.com
Issa Hendrix   issa.hendrix@example.com
Grace Turner   grace.turner@example.com
Brigitta Pierre   brigitta.pierre@example.com

## Exercise 1
In this Exercise, generate photos of the random 10 users.

In [9]:
## Write your code here
for user in some_list:
    print (user.get_picture())

https://randomuser.me/api/portraits/women/80.jpg
https://randomuser.me/api/portraits/men/66.jpg
https://randomuser.me/api/portraits/men/84.jpg
https://randomuser.me/api/portraits/women/92.jpg
https://randomuser.me/api/portraits/men/32.jpg
https://randomuser.me/api/portraits/women/0.jpg
https://randomuser.me/api/portraits/women/5.jpg
https://randomuser.me/api/portraits/men/92.jpg
https://randomuser.me/api/portraits/women/60.jpg
https://randomuser.me/api/portraits/women/62.jpg

<details><summary>Click here for the solution</summary>

```python
for user in some_list:
    print (user.get_picture())
```

</details>

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [10]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [12]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Kerim Balaban,male,Bingöl,Bolu,kerim.balaban@example.com,1973-10-16T13:22:13.137Z,https://randomuser.me/api/portraits/men/37.jpg
1,Shelly Stephens,female,Busselton,Queensland,shelly.stephens@example.com,1961-02-28T14:56:50.265Z,https://randomuser.me/api/portraits/women/6.jpg
2,آراد کریمی,male,ملارد,همدان,ard.khrymy@example.com,1969-07-02T02:42:26.724Z,https://randomuser.me/api/portraits/men/17.jpg
3,Arianna Kelley,female,Elizabeth,Illinois,arianna.kelley@example.com,1973-12-27T15:12:41.577Z,https://randomuser.me/api/portraits/women/25.jpg
4,Darryl Lucas,male,Durham,Tayside,darryl.lucas@example.com,1990-02-18T11:11:26.931Z,https://randomuser.me/api/portraits/men/75.jpg
5,Klaus-Günter Arendt,male,Bad Colberg-Heldburg,Schleswig-Holstein,klaus-gunter.arendt@example.com,1956-08-22T06:05:12.292Z,https://randomuser.me/api/portraits/men/52.jpg
6,Sócrates Lima,male,Simões Filho,Rio Grande do Norte,socrates.lima@example.com,1967-07-31T16:17:01.732Z,https://randomuser.me/api/portraits/men/91.jpg
7,Babür Durmaz,male,Antalya,Van,babur.durmaz@example.com,1946-02-14T21:33:06.011Z,https://randomuser.me/api/portraits/men/57.jpg
8,Onur Kahveci,male,Tekirdağ,Aksaray,onur.kahveci@example.com,1946-03-23T02:18:06.867Z,https://randomuser.me/api/portraits/men/59.jpg
9,Eleanor Parker,female,Stoke-on-Trent,Dyfed,eleanor.parker@example.com,1992-12-11T13:54:02.552Z,https://randomuser.me/api/portraits/women/73.jpg

In [13]:
df1 = pd.DataFrame(get_users())  
df1

,Name,Gender,City,State,Email,DOB,Picture
0,Sidónio Lopes,male,Rio de Janeiro,Roraima,sidonio.lopes@example.com,1985-02-13T16:36:06.463Z,https://randomuser.me/api/portraits/men/79.jpg
1,Noémie Addy,female,Delta,Yukon,noemie.addy@example.com,1970-05-24T22:40:33.692Z,https://randomuser.me/api/portraits/women/5.jpg
2,Grace Lee,female,Whangarei,Otago,grace.lee@example.com,1947-08-08T08:59:23.330Z,https://randomuser.me/api/portraits/women/37.jpg
3,Cora da Cunha,female,Feira de Santana,Ceará,cora.dacunha@example.com,1945-12-27T18:43:40.169Z,https://randomuser.me/api/portraits/women/95.jpg
4,Marvin Davidson,male,Balbriggan,Waterford,marvin.davidson@example.com,1950-03-10T04:55:27.720Z,https://randomuser.me/api/portraits/men/39.jpg
5,Aaron Curtis,male,Bathurst,Australian Capital Territory,aaron.curtis@example.com,1975-02-10T06:47:17.298Z,https://randomuser.me/api/portraits/men/1.jpg
6,Jeremiah Hall,male,New Ross,Cork City,jeremiah.hall@example.com,1955-02-27T12:23:11.204Z,https://randomuser.me/api/portraits/men/1.jpg
7,Asta Petersen,female,Jystrup,Syddanmark,asta.petersen@example.com,1972-02-13T06:03:26.778Z,https://randomuser.me/api/portraits/women/23.jpg
8,Luciana Renard,female,Montpreveyres,Uri,luciana.renard@example.com,1963-01-07T03:38:55.430Z,https://randomuser.me/api/portraits/women/58.jpg
9,Eduardo Esteban,male,Pozuelo de Alarcón,Comunidad Valenciana,eduardo.esteban@example.com,1963-11-23T11:23:21.418Z,https://randomuser.me/api/portraits/men/89.jpg

Now we have a *pandas* dataframe that can be used for any testing purposes that the tester might have.

## Example 2: Fruityvice API

Another, more common way to use APIs, is through `requests` library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [14]:
import requests
import json

We will obtain the [fruityvice](https://www.fruityvice.com) API data using `requests.get("url")` function. The data is in a json format.

In [15]:
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")

We will retrieve results using `json.loads()` function.

In [16]:
results = json.loads(data.text)

We will convert our json data into *pandas* data frame.

In [17]:
pd.DataFrame(results)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [18]:
df2 = pd.json_normalize(results)

In [19]:
df2

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

Let's see if we can extract some information from this dataframe. Perhaps, we need to know the family and genus of a cherry.

In [23]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

## Exercise 2
In this Exercise, find out how many calories are contained in a banana.

In [25]:
# Write your code here
banana = df2.loc[df2["name"] == 'Banana']
(banana.iloc[0]['nutritions.calories'])

np.int64(96)

<details><summary>Click here for the solution</summary>

```python
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']
```

</details>

## Exercise 3

This [page](https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/) contains a list of free public APIs for you to practice. Let us deal with the following example.

#### Official Joke API 
This API returns random jokes from a database. The following URL can be used to retrieve 10 random jokes.

https://official-joke-api.appspot.com/jokes/ten

1. Using `requests.get("url")` function, load the data from the URL.

In [28]:
# Write your code here
import requests
data = requests.get("https://official-joke-api.appspot.com/jokes/ten")
data

<details><summary>Click here for the solution</summary>

```python
data2 = requests.get("https://official-joke-api.appspot.com/jokes/ten")
```

</details>

2. Retrieve results using `json.loads()` function.

In [30]:
# Write your code here
results = json.loads(data.text)
results

[{'type': 'programming',
  'setup': 'What is the most used language in programming?',
  'punchline': 'Profanity.',
  'id': 381},
 {'type': 'programming',
  'setup': "What's the best thing about a Boolean?",
  'punchline': "Even if you're wrong, you're only off by a bit.",
  'id': 15},
 {'type': 'general',
  'setup': 'What is the difference between ignorance and apathy?',
  'punchline': "I don't know and I don't care.",
  'id': 244},
 {'type': 'general',
  'setup': 'When does a joke become a dad joke?',
  'punchline': 'When it becomes apparent.',
  'id': 281},
 {'type': 'general',
  'setup': 'Why are “Dad Jokes” so good?',
  'punchline': 'Because the punchline is apparent.',
  'id': 375},
 {'type': 'general',
  'setup': "did you know the first French fries weren't cooked in France?",
  'punchline': 'they were cooked in Greece',
  'id': 31},
 {'type': 'general',
  'setup': "Due to complaints, Hawaii passed a law where you're not allowed to laugh above a certain decibel.",
  'punchline': 'You can only use a low ha.',
  'id': 403},
 {'type': 'general',
  'setup': 'What do you call a bee that lives in America?',
  'punchline': 'A USB.',
  'id': 192},
 {'type': 'programming',
  'setup': 'How do you generate a random string?',
  'punchline': 'Put a Windows user in front of Vim and tell them to exit.',
  'id': 405},
 {'type': 'general',
  'setup': 'What do you get hanging from Apple trees?',
  'punchline': 'Sore arms.',
  'id': 228}]

<details><summary>Click here for the solution</summary>

```python
results2 = json.loads(data2.text)
```

</details>

3. Convert json data into *pandas* data frame. Drop the type and id columns.

In [36]:
# Write your code here
df=pd.DataFrame(results)
df.drop(['type'])

,type,setup,punchline,id
0,programming,What is the most used language in programming?,Profanity.,381
1,programming,What's the best thing about a Boolean?,"Even if you're wrong, you're only off by a bit.",15
2,general,What is the difference between ignorance and a...,I don't know and I don't care.,244
3,general,When does a joke become a dad joke?,When it becomes apparent.,281
4,general,Why are “Dad Jokes” so good?,Because the punchline is apparent.,375
5,general,did you know the first French fries weren't co...,they were cooked in Greece,31
6,general,"Due to complaints, Hawaii passed a law where y...",You can only use a low ha.,403
7,general,What do you call a bee that lives in America?,A USB.,192
8,programming,How do you generate a random string?,Put a Windows user in front of Vim and tell th...,405
9,general,What do you get hanging from Apple trees?,Sore arms.,228

<details><summary>Click here for the solution</summary>

```python
df3 = pd.DataFrame(results2)
df3.drop(columns=["type","id"],inplace=True)
df3
```

</details>

# Congratulations! - You have completed the lab

## Author
<a href="https://www.linkedin.com/in/svitlana-kramar" target="_blank">Svitlana Kramar</a>

Svitlana is a master’s degree Data Science and Analytics student at University of Calgary, who enjoys travelling, learning new languages and cultures and loves spreading her passion for Data Science.

## Additional Contributor
<a href="https://www.linkedin.com/in/abhishek-gagneja-23051987/" target="_blank">Abhishek Gagneja</a>

Copyright © 2023 IBM Corporation. All rights reserved.